// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1lA2TnGbYOqJwqvBU8l6Z9F6gkbqFZBc',
    appId: '1:461936537433:web:38a16e6e84d0e2fa4ca826',
    messagingSenderId: '461936537433',
    projectId: 'rps-claim-manager-1f250',
    authDomain: 'rps-claim-manager-1f250.firebaseapp.com',
    storageBucket: 'rps-claim-manager-1f250.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfAVsv5Mz8COqTem5E-KkbFaW92pvvBfo',
    appId: '1:99995806902:android:6c4aa7405e1cc447410a17',
    messagingSenderId: '99995806902',
    projectId: 'rps-claim-manager-1f250',
    storageBucket: 'rps-claim-manager-1f250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCTQ_fR1SzugeNaqBbI-gASHca-zlHSE',
    appId: '1:99995806902:ios:6c4aa7405e1cc447410a17',
    messagingSenderId: '99995806902',
    projectId: 'rps-claim-manager-1f250',
    storageBucket: 'rps-claim-manager-1f250.firebasestorage.app',
    iosBundleId: 'com.claimmanager.claims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCTQ_fR1SzugeNaqBbI-gASHca-zlHSE',
    appId: '1:99995806902:ios:6c4aa7405e1cc447410a17',
    messagingSenderId: '99995806902',
    projectId: 'rps-claim-manager-1f250',
    storageBucket: 'rps-claim-manager-1f250.firebasestorage.app',
    iosBundleId: 'com.claimmanager.claims',
  );
}
